version: '3'
services:
  caddy:
    image: abiosoft/caddy:1.0.4-no-stats
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ./caddy/certs:/root/.caddy
    ports:
      - 80:80
      - 443:443